# Generated by Django 4.2.2 on 2023-06-23 03:33

import FayTourApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(default='')),
                ('coordinatesX', models.FloatField(default=0.0)),
                ('coordinatesY', models.FloatField(default=0.0)),
                ('originalImage', models.ImageField(upload_to='image')),
                ('address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('TotalBeds', models.IntegerField(default=0)),
                ('Phone', models.CharField(max_length=500, unique=True)),
                ('web', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Single', models.IntegerField(default=0)),
                ('Double', models.IntegerField(default=0)),
                ('Triple', models.IntegerField(default=0)),
                ('Sweet', models.IntegerField(default=0)),
                ('chalet', models.IntegerField(default=0)),
                ('villa', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('type', models.CharField(max_length=500)),
                ('description', models.TextField(default='')),
                ('coordinatesX', models.FloatField()),
                ('coordinatesY', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('originalImage', models.ImageField(upload_to='image/%y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coordinatesX', 'coordinatesY')},
            },
        ),
        migrations.CreateModel(
            name='TourismImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, unique=True, upload_to='image')),
                ('touristPlaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FayTourApp.touristplaces')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', unique=True, upload_to=FayTourApp.models.get_unique_filename)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FayTourApp.post')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, unique=True, upload_to='image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FayTourApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTouristPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('touristPlaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.touristplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateTouristPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('touristPlaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.touristplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'touristPlaces')},
                'index_together': {('user', 'touristPlaces')},
            },
        ),
        migrations.CreateModel(
            name='RateHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hotel')},
                'index_together': {('user', 'hotel')},
            },
        ),
    ]
