# Generated by Django 4.2.2 on 2023-06-24 18:22

import FayTourApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='originalImage',
            field=models.ImageField(upload_to=FayTourApp.models.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='hotelsimages',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to=FayTourApp.models.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='tourismimages',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to=FayTourApp.models.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='touristplaces',
            name='originalImage',
            field=models.ImageField(upload_to=FayTourApp.models.get_unique_filename),
        ),
    ]
