# Generated by Django 3.2 on 2023-06-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0004_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
