# Generated by Django 3.2 on 2023-06-26 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FayTourApp', '0013_auto_20230626_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteTouristPlaces',
            new_name='FavoriteTouristPlace',
        ),
    ]
