# Generated by Django 3.2 on 2023-06-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0014_rename_favoritetouristplaces_favoritetouristplace'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritetouristplace',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='favoritetouristplace',
            index_together=set(),
        ),
    ]
