# Generated by Django 3.2 on 2023-06-26 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FayTourApp', '0015_auto_20230626_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteTouristPlace',
            new_name='FavoriteTouristPlaces',
        ),
    ]
