# Generated by Django 3.2 on 2023-06-26 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FayTourApp', '0016_rename_favoritetouristplace_favoritetouristplaces'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritetouristplaces',
            unique_together={('user', 'touristPlaces')},
        ),
        migrations.AlterIndexTogether(
            name='favoritetouristplaces',
            index_together={('user', 'touristPlaces')},
        ),
    ]
