# Generated by Django 3.2 on 2023-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0017_auto_20230626_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratehotel',
            name='stars',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
