# Generated by Django 3.2 on 2023-06-26 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0018_alter_ratehotel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratehotel',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Stars must be between 1 and 5.'), django.core.validators.MaxValueValidator(5, message='Stars must be between 1 and 5.')]),
        ),
    ]
