# Generated by Django 3.2 on 2023-07-22 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FayTourApp', '0021_likepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='likepost',
            name='index',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='originalImage',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hotelsimages',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='tourismimages',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='touristplaces',
            name='originalImage',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelreservation',
            unique_together={('user', 'hotel')},
        ),
        migrations.AlterIndexTogether(
            name='hotelreservation',
            index_together={('user', 'hotel')},
        ),
    ]
