# Generated by Django 3.2 on 2023-07-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0022_auto_20230722_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='index',
        ),
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.CharField(default='', max_length=500),
        ),
    ]
